export const SEASONS = {
  SPRING: "Spring",
  SUMMER: "Summer",
  FALL: "Fall",
  WINTER: "Winter",
};

export const FLOWER_NAMES = {
  LAVENDER: "Lavender",
  MARIGOLD: "Marigold",
  DAISY: "Daisy",
  TULIP: "Tulip",
  SUNFLOWER: "Sunflower",
  PEONY: "Peony",
  ZINNIA: "Zinnia",
  ROSE: "Rose",
  CROCUS: "Crocus",
  BABYSBREATH: "Baby's Breath",
  BEGONIA: "Begonia",
  HYDRANGEA: "Hydrangea",
  RANUNCULUS: "Ranunculus",
  CARNATION: "Carnation",
  BACHELORSBUTTON: "Bachelor's Button",
  LISIANTHUS: "Lisianthus",
  DAFFODIL: "Daffodils",
  LILLY: "Lilly",
  SNAPDRAGON: "Snapdragon",
  COSMOS: "Cosoms",
  DAHLIA: "Dahlia",
  ANEMONE: "Anemone",
  ORCHID: "Orchid",
  FERN: "Fern",
  CALADIUM: "Caladium",
  COLEUS: "Coleus",
  IMPATIEN: "Impatien",
  HYACINTH: "Hyacinth",
};

export const LIGHT = {
  FULLSUN: "☀️ Full sun",
  SHADE: "☁️ Shade",
  PARTIALSHADE: "🌤️ Partial shade",
  FULLTOPART: "☀️ Full sun to partial shade",
};

export const flowers = [
  {
    flowerName: FLOWER_NAMES.LAVENDER,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING, SEASONS.SUMMER, SEASONS.FALL],
    zones: [5, 6, 7, 8, 9, 10, 11],
    indoorSowWeeks: [10, 12],
    outdoorSowWeeks: [4, 6],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.PEONY,
      FLOWER_NAMES.RANUNCULUS,
      FLOWER_NAMES.CARNATION,
    ],
    imageUrl: "images/single_lavender_flower.webp",
  },
  {
    flowerName: FLOWER_NAMES.MARIGOLD,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING, SEASONS.SUMMER, SEASONS.FALL],
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    indoorSowWeeks: [6, 8],
    outdoorSowWeeks: [1, 2],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.PEONY,
      FLOWER_NAMES.LAVENDER,
      FLOWER_NAMES.BACHELORSBUTTON,
    ],
    imageUrl: "images/marigolds.webp",
  },
  {
    flowerName: FLOWER_NAMES.DAISY,
    watering: "💧 Every 1-2 days",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING, SEASONS.SUMMER, SEASONS.FALL],
    zones: [4, 5, 6, 7, 8, 9, 10],
    indoorSowWeeks: [6, 8],
    outdoorSowWeeks: [2, 4],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.BABYSBREATH,
      FLOWER_NAMES.HYDRANGEA,
      FLOWER_NAMES.LISIANTHUS,
    ],
    imageUrl: "images/daisies.webp",
  },
  {
    flowerName: FLOWER_NAMES.TULIP,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.FALL],
    zones: [2, 3, 4, 5, 6, 7, 8],
    indoorSowWeeks: [6, 8],
    outdoorSowWeeks: [6, 8],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.HYACINTH,
      FLOWER_NAMES.DAFFODIL,
      FLOWER_NAMES.LILLY,
    ],
    imageUrl: "images/tulip.webp",
  },
  {
    flowerName: FLOWER_NAMES.SUNFLOWER,
    watering: "💧 Every 1-2 days",
    light: LIGHT.FULLSUN,
    season: [SEASONS.SPRING, SEASONS.SUMMER, SEASONS.FALL],
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    indoorSowWeeks: [4, 6],
    outdoorSowWeeks: [1, 2],
    bouquet: [
      FLOWER_NAMES.BABYSBREATH,
      FLOWER_NAMES.DAISY,
      FLOWER_NAMES.SNAPDRAGON,
      FLOWER_NAMES.LAVENDER,
    ],
    imageUrl: "images/sunflower.webp",
  },
  {
    flowerName: FLOWER_NAMES.PEONY,
    watering: "💧 Every other week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.FALL],
    zones: [3, 4, 5, 6, 7, 8],
    indoorSowWeeks: [4, 6],
    outdoorSowWeeks: [6, 8],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.BABYSBREATH,
      FLOWER_NAMES.HYDRANGEA,
      FLOWER_NAMES.LISIANTHUS,
    ],
    imageUrl: "images/peony.webp",
  },
  {
    flowerName: FLOWER_NAMES.ZINNIA,
    watering: "💧Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING],
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    indoorSowWeeks: [4, 6],
    outdoorSowWeeks: [1, 2],
    bouquet: [
      FLOWER_NAMES.COSMOS,
      FLOWER_NAMES.BABYSBREATH,
      FLOWER_NAMES.MARIGOLD,
      FLOWER_NAMES.DAHLIA,
    ],
    imageUrl: "images/zinnias.jpg",
  },
  {
    flowerName: FLOWER_NAMES.ROSE,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING, SEASONS.WINTER],
    zones: [5, 6, 7, 8, 9, 10],
    indoorSowWeeks: [6, 8],
    outdoorSowWeeks: [6],
    bouquet: [
      FLOWER_NAMES.LILLY,
      FLOWER_NAMES.BABYSBREATH,
      FLOWER_NAMES.HYDRANGEA,
      FLOWER_NAMES.CARNATION,
    ],
    imageUrl: "images/roses.webp",
  },
  {
    flowerName: FLOWER_NAMES.CROCUS,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.FALL],
    zones: [3, 4, 5, 6, 7, 8],
    indoorSowWeeks: [12, 15],
    outdoorSowWeeks: [6, 8],
    bouquet: [
      FLOWER_NAMES.TULIP,
      FLOWER_NAMES.DAFFODIL,
      FLOWER_NAMES.HYACINTH,
      FLOWER_NAMES.ANEMONE,
    ],
    imageUrl: "images/crocus.webp",
  },
  {
    flowerName: FLOWER_NAMES.BABYSBREATH,
    watering: "💧 Once a week",
    light: LIGHT.FULLTOPART,
    season: [SEASONS.SPRING, SEASONS.SUMMER, SEASONS.FALL],
    zones: [3, 4, 5, 6, 7, 8, 9],
    indoorSowWeeks: [6, 8],
    outdoorSowWeeks: [1, 2],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.PEONY,
      FLOWER_NAMES.ORCHID,
      FLOWER_NAMES.HYDRANGEA,
    ],
    imageUrl: "images/babys-breath.webp",
  },
  {
    flowerName: FLOWER_NAMES.BEGONIA,
    watering: "💧 Once or twice a week",
    light: LIGHT.PARTIALSHADE,
    season: [SEASONS.SPRING],
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    indoorSowWeeks: [8, 10],
    outdoorSowWeeks: [8, 12],
    bouquet: [
      FLOWER_NAMES.FERN,
      FLOWER_NAMES.CALADIUM,
      FLOWER_NAMES.COLEUS,
      FLOWER_NAMES.IMPATIEN,
    ],
    imageUrl: "images/begonias.webp",
  },
  {
    flowerName: FLOWER_NAMES.HYDRANGEA,
    watering: "💧 Once a week",
    light: LIGHT.PARTIALSHADE,
    season: [SEASONS.SPRING],
    zones: [3, 4, 5, 6, 7, 8, 9],
    indoorSowWeeks: [6, 10],
    outdoorSowWeeks: [6,8],
    bouquet: [
      FLOWER_NAMES.ROSE,
      FLOWER_NAMES.PEONY,
      FLOWER_NAMES.LILLY,
      FLOWER_NAMES.TULIP,
    ],
    imageUrl: "images/hydrangeas.webp",
  },
];
